In [1]:
# LIBRARIES IS COLLECTION OD PRE-COMBINED CODE/MODULE/FUNCTION TO REDUCE TIME .


# Numpy
# --------------------------

# NumPy is a Python library used for working with arrays. with fast easy and efficient way.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.


# why we need numpy?
# --------------------------

# we work on large dataset in python it slow and use loop .

# in python bulit in list use but for large dataset it not memory efficient

In [2]:
import numpy as np

In [3]:
import time

a= [1,2,3,4,5,6,7,8,9,10] *100000
start= time.time()

for i in range(len(a)):
    a[i] = a[i]*2

print("\nTime taken for list:", time.time() - start)


Time taken for list: 0.06699895858764648


In [4]:
# Python list 
a= [1,2,3,4,5,6,7,8,9,10]
b=np.array(a)
start=time.time()
new_b= b*2

total_time=time.time() - start

print("\nTime taken for list:", time.time() - start)



Time taken for list: 0.0009996891021728516


In [5]:
# Why NumPy is Faster than Lists
# ------------------------------------

# • 	Implementation in C
# NumPy is built using C (and Fortran).
# Runs closer to machine code → faster execution.



In [6]:
import sys
a=[1,2,3,4,5]
arr = np.array(a)

print("List size:",sys.getsizeof(a))

print("Array size:", arr.nbytes)

List size: 104
Array size: 20


In [7]:
# • 	Contiguous Memory Allocation
# NumPy arrays store data in one continuous block of memory.
# Easy for CPU to access → faster operations.
# Python lists store scattered references → slower.

In [8]:
# Direct operation - Vectorization


# Vectorization → NumPy can do math on the whole array at once, not one-by-one in a loop.
#  Example:  doubles all elements instantly.


In [9]:
# Datatypes:

# Python list - Allowed mix datatypes
# Numpy array - same datatypes


In [10]:
a= [1,'s',"sample",3.1]
print(type(a))

<class 'list'>


In [11]:
# Create array from list
arr = np.array(a)
print(arr)
b=type(arr)
print(b)

['1' 's' 'sample' '3.1']
<class 'numpy.ndarray'>


In [12]:
# List of temperatures
temperature = [23, 45, 33, 43, 38]


total = 0
for temp in temperature:
    total += temp
average = total / len(temperature)
print("Average temperature:", average)


Average temperature: 36.4


In [13]:
# for this its easy run by using loop but if data is very large may take many times.
# for solving this issue numpy invented.
# where numpy introduced arrays which is fast and memory efficient as compared to list

In [14]:
# let see how numpy solve this issue

temperature = np.array([32.4,34,38,34.6,39])
average = np.mean(temperature)
print(average)

35.6


In [15]:
# That easy handle large datasets
# Numerical python

# Features of NumPy:
# ------------------------------------------------------


# speed 50 to 100 time faster than lists
# less memory
# easy math operation
# usages in fields data science , ml and ai ,stockmarket and finance and medical rrsearch and image processing.



# list vs numpy array
# --------------------------------------------------------

# speed              slow              50-100times
# Datatypes          allowed mixed     same datatypes
# memory required    more              less
# calculation        neeed loop        easy calculation by using operations(direct-vectorization)
# best usages        small data        larges datasets
# Built-in function  Limited           Many powerful


In [16]:
# Array

# 1.arrray is collection of homogenous data element that is stored in cotingous memory location.
# 2.it is like list data structure in python
# 3.it also use[] to represent the data element
# 4.Numpy's array class is called ndarray.

In [17]:
# Create a NumPy array
arr1 = np.array([1, 2, 3, 4, 5])

# Display the array and its type
print("Array:", arr1)
print("Type:", type(arr1))

# NumPy array properties
print("Total memory (bytes):", arr1.nbytes)      # total memory used by array
print("Data type:", arr1.dtype)                  # data type of each element
print("Dimensions:", arr1.ndim)                  # number of dimensions
print("Item size (bytes):", arr1.itemsize)       # size of each element in bytes
print("Total size (bytes):", arr1.nbytes)        # total size in bytes
print("Number of elements:", arr1.size)          # total number of elements
print("Shape:", arr1.shape)                      # shape of the array


Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Total memory (bytes): 20
Data type: int32
Dimensions: 1
Item size (bytes): 4
Total size (bytes): 20
Number of elements: 5
Shape: (5,)


In [18]:
# Convert the datatypes of int64 to float32
arr00 = np.array([1,2,3,4,5] , dtype= np.float32)
print(arr00)

[1. 2. 3. 4. 5.]


In [19]:
arr00.dtype

dtype('float32')

In [20]:
arr001 = np.array([1,2,3,4,5] , dtype= np.int32)
print(arr001)

[1 2 3 4 5]


In [21]:
arr001.dtype # default datatypes of integers in int 64/int32

dtype('int32')

In [22]:
arr.dtype # default datatypes of float64

arr400=np.array([1.8,2.8,3.6,4.2,5.8])
print(arr400)
arr400.dtype

[1.8 2.8 3.6 4.2 5.8]


dtype('float64')

In [23]:
# type casting -> astype()

arrr=np.array([1,2,3,4,5])
print(arrr)
print(arrr.dtype)

[1 2 3 4 5]
int32


In [24]:
arr001 = arrr.astype(np.float64)
arr001

array([1., 2., 3., 4., 5.])

In [25]:
arr001.dtype

dtype('float64')

In [26]:
# Type Casting errors:

arr33= ["1", "hello" ,"2" ]
arr99=arr33.astype(np.int32)
arr99

AttributeError: 'list' object has no attribute 'astype'

In [ ]:
aa1=np.array([])
aa1.ndim              # 1D array

1

In [ ]:
aa2=np.array([[]])  # 2D arrray (1 row,0 column)
aa2.ndim

2

In [ ]:
# one dimensional array is like list or row of matrix
arr2=np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


In [ ]:
# multi dimensional array is like matrix or table
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr3.shape # shape of array

(3, 3)

In [ ]:
arr3.ndim # dimension of array

2

In [ ]:
arr3.size # size of array

9

In [ ]:
arr.itemsize # - Returns the size (in bytes) of each element in the NumPy array.


8

In [ ]:
# 2 dimensional array
arr4=np.array([[1,2,3],[4,5,6]])
print(arr4)

[[1 2 3]
 [4 5 6]]


In [ ]:
# List
list1=[1,2,3,4,5]
print(list1)
# -------------------
# Numpy array
arr1=np.array([1,2,3,4,5])
print(arr1)

# here we see both are similar but in background they are different because array store data in efficient way.

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
# Create Array from list

arr5=np.array(list1)
print(arr5)

# with default values

arr6=np.zeros(4) # create 1D array with 4 elements with default value 0
print(arr6)

[1 2 3 4 5]
[0. 0. 0. 0.]


In [ ]:
# zeros(shape)

arr70=np.zeros(5) # 3 rows and 4 columns
print(arr70)
print("------------------")
arr7=np.zeros((3,4)) # 3 rows and 4 columns
print(arr7)

[0. 0. 0. 0. 0.]
------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones(shape)

arr8=np.ones((2,3)) # 2 rows and 3 columns with default value 1
print(arr8)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# full(shape,fill_value)
# - shape = (rows, columns)
# - fill_value = value to fill in every cell

arr90=np.full(7,2) # 2 rows and 3 columns with default value 7
print(arr90)


arr9=np.full((2,3),7) # 2 rows and 3 columns with default value 7
print(arr9)

[2 2 2 2 2 2 2]
[[7 7 7]
 [7 7 7]]


In [ ]:
# Empty Function

arr=np.empty((5,3))
print(arr)

# np.zeros(shape): Creates an array of the specified shape, filled with zeros. Each element is explicitly set to 0, ensuring predictable values.

# np.empty(shape): Allocates memory for an array of the specified shape but does not initialize its values.
# This means the array might contain arbitrary (random) values that were already present in that memory space.


In [ ]:
# creating sequences of numbers in numpy
# ------------------------------------------------------
arr10=np.arange(1,10) # 1 to 9  # it doesnot include 10
print(arr10)



[1 2 3 4 5 6 7 8 9]


In [ ]:
# Identity matrix

# np.eye(n) creates an n x n identity matrix


arr11=np.eye(3) # 3x3 identity matrix
print(arr11)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Array Shaping: Reshape,Ravel,flatten

# reshape():
# - Changes the shape of an array without modifying data
# - Returns a view when possible
# - Total elements must match: rows × columns = original size

import numpy as np

# Original 1D array
arr12 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Original arr12:", arr12)

# Attempt to reshape to 3x5 (invalid: 8 elements ≠ 15)
# This line will raise an error if uncommented
# arr12.reshape(3, 5)

print(" ")

# Valid reshape: 15 elements → 3x5 matrix
arr3 = np.arange(15).reshape((3, 5))
print("arr3 (3x5):\n", arr3)

# 48 elements → 3x4x4 tensor (3 blocks of 4x4)
arr4 = np.arange(48).reshape((3, 4, 4))
print("arr4 (3x4x4):\n", arr4)

# 12 elements → reshape to 3x4
arr5 = np.arange(12)
arr6 = np.reshape(arr5, (3, 4))
print("arr6 (3x4):\n", arr6)



Original arr12: [1 2 3 4 5 6 7 8]
 
arr3 (3x5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
arr4 (3x4x4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
arr6 (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# resize
# resize():

# Modifies the array in place, affecting the original array directly.
# If the new size is larger, it fills extra elements with zeros.

# If the new size is smaller, it truncates extra elements.

# Does not require the original array to have a compatible shape.

ar=np.arange(15)
ar.resize(3,4)
print(ar)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Identity Function

ar=np.identity(5)
print(ar)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Eye function

# it is genenratization of identity matrix

ar=np.eye(4,5)
print(ar)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
# Linspace() function

# np.linspace() is used to create an array of evenly spaced values over a specified range.
# - Syntax: np.linspace(start, stop, num)
# - num → number of values


arr15=np.linspace(1,5,6)
print(arr15)
arr16=np.linspace(0,2*np.pi*100)
print(arr16)

[1.  1.8 2.6 3.4 4.2 5. ]
[  0.          12.82282716  25.64565432  38.46848147  51.29130863
  64.11413579  76.93696295  89.7597901  102.58261726 115.40544442
 128.22827158 141.05109873 153.87392589 166.69675305 179.51958021
 192.34240736 205.16523452 217.98806168 230.81088884 243.63371599
 256.45654315 269.27937031 282.10219747 294.92502462 307.74785178
 320.57067894 333.3935061  346.21633325 359.03916041 371.86198757
 384.68481473 397.50764188 410.33046904 423.1532962  435.97612336
 448.79895051 461.62177767 474.44460483 487.26743199 500.09025914
 512.9130863  525.73591346 538.55874062 551.38156777 564.20439493
 577.02722209 589.85004925 602.6728764  615.49570356 628.31853072]


In [ ]:
# # Logspace() function

# Logspace() function  used to creates numbers spaced evenly on a log scale (powers of 10).

import numpy as np
# - Syntax: np.logspace(start, stop, num, base=10)


arr171 = np.logspace(1, 3, 6)   # 5 values between 10^1 and 10^3
print(arr171)   # [10. 31.62 100. 316.22 1000.]



[  10.           25.11886432   63.09573445  158.48931925  398.10717055
 1000.        ]


In [ ]:
# Empty_like() function - it create copy
import numpy as np
a1=np.arange(9)
print(a1)
a2=np.empty_like(a1)
print(a2)
a2[4]=200
print(a2)
print(a1)



[0 1 2 3 4 5 6 7 8]
[ 1  2 -3 -8  6 -4  6 -4  6]
[  1   2  -3  -8 200  -4   6  -4   6]
[0 1 2 3 4 5 6 7 8]


In [ ]:
#  Ravel function()- Convert into 1D Array

# - Returns a view of the original array

# - Connection exists → changes in the raveled array can reflect back in the original.

# The ravel() function in NumPy does not always create a copy—it flattens an array into a 1D representation,
# but whether it returns a copy or a view depends on the array's memory layout.
import numpy as np
a177=np.array([[3,4,5],[1,2,3]])
print(a177)
print(a177.ndim)


a2=np.ravel(a177)
print(a2)
a2[4]=200
print(a2)
print(a1)



[[3 4 5]
 [1 2 3]]
2
[3 4 5 1 2 3]
[  3   4   5   1 200   3]
[  0   1   2   3 200   5   6   7   8]


In [ ]:
# flatten() :- — Convert Multi-Dimensional Array to 1D

# Returns a copy of the array collapsed into one dimension.
# - No connection → changes in the flattened array do not affect the original.




import numpy as np

a178 = np.array([[12,33,78],[67,45,76]])
print(a178)

a2 = a178.flatten()
print(a2)

a178[0,0] = 200
print(a2)




[[12 33 78]
 [67 45 76]]
[12 33 78 67 45 76]
[12 33 78 67 45 76]


In [ ]:
# using flat attribute/iterator

# Provides a 1D iterator over all elements of a NumPy array, regardless of its shape.

a1=np.arange(12).reshape(3,4)
print(a1)
for i in a1.flat:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
# diag() function:-

# Syntax: np.diag(v, k=0)

# Purpose:
# • 	Extracts the diagonal from a matrix
# • 	OR creates a diagonal matrix from a 1D array

a1=np.diag([2,3,4])
print(a1)


# passing 2d array
a=np.arange(10,19).reshape(3,3)
print(a)
b=np.diag(a)
print(b)
c=np.diag(b)
print(c)


[[2 0 0]
 [0 3 0]
 [0 0 4]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[10 14 18]
[[10  0  0]
 [ 0 14  0]
 [ 0  0 18]]


In [ ]:
# random function
d=np.random.rand(10)   # random floats(0 to 1)
print(d)

#

n=np.random.default_rng()
d=n.random((2,4))
print(d)

[0.02014208 0.98034217 0.59216364 0.04755914 0.19956618 0.76439033
 0.78574426 0.7262864  0.90252593 0.43415117]
[[0.90183469 0.49186409 0.19721737 0.03238166]
 [0.01380905 0.08122786 0.92848281 0.49529644]]


In [ ]:
# using randn() fn -> random floats from standard normal distribution

a=np.random.randn(2,3)
print(a)

[[ 0.1262456   0.42564976 -0.65555496]
 [-1.20345438 -0.08429267 -2.41898308]]


In [ ]:
# using randint() fn

a=np.random.randint(2,10, size=(3,5,2))
print(a)

[[[7 8]
  [2 7]
  [5 7]
  [2 6]
  [6 6]]

 [[6 5]
  [4 5]
  [9 5]
  [2 5]
  [3 6]]

 [[7 4]
  [3 8]
  [3 4]
  [4 2]
  [4 9]]]


In [ ]:
arry=np.random.randint(10,100)
arry

70

In [ ]:
# Arithemetic Operation
import numpy as np

a1 = np.array([[1,2,3],[3,4,5],[5,4,3]])

print(a1)
print(a1 + 6)
print(a1 - 2)
print(a1 * 3)
print(a1 / 2)
print(a1 // 3)
print(a1 % 5)

print(a1 ** 3)
print(a1 ** 0.5)
print(a1.T)


[[1 2 3]
 [3 4 5]
 [5 4 3]]
[[ 7  8  9]
 [ 9 10 11]
 [11 10  9]]
[[-1  0  1]
 [ 1  2  3]
 [ 3  2  1]]
[[ 3  6  9]
 [ 9 12 15]
 [15 12  9]]
[[0.5 1.  1.5]
 [1.5 2.  2.5]
 [2.5 2.  1.5]]
[[0 0 1]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [3 4 0]
 [0 4 3]]
[[  1   8  27]
 [ 27  64 125]
 [125  64  27]]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]
 [2.23606798 2.         1.73205081]]
[[1 3 5]
 [2 4 4]
 [3 5 3]]


In [ ]:
# a1 a2 a1+a2   (np.add(a1,a2)
# a1-a2
# a1*a2
# a1.a2
# a1@a2
# mutiplication of two matrix by using matmul() function of linalg of linalg
# np.linalg.linalg.matmul(a1,a2)


import numpy as np


a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])


sum_result = np.add(a1, a2)
sub_result = a1 - a2
mul_result = a1 * a2
dot_result = np.dot(a1, a2)
matmul_result = a1 @ a2


linalg_matmul_result = np.linalg.matmul(a1, a2)


print(sum_result)
print(sub_result)
print(mul_result)
print(dot_result)
print(matmul_result)
print(linalg_matmul_result)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# Reading and writing data of files
# 1. reading from files:it is loading from any files
# 2.writing it is the saving the data from numpy to files.

a = np.arange(15).reshape(3, 5)
print(a)

# Save array to text file with header and footer


# ============================================================================================================================
# syntax:-
# np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')



# np.savetxt(
#     "B:/BCA I/CFN/Assignment_I.txt",  # File path
#     data,                             # Array to save
#     fmt="%d",                         # Save as integers
#     delimiter=",",                   # Use comma as separator
#     newline="\n",                    # Line break after each row
#     header="My Data",                # Header line
#     footer="End of File",            # Footer line
#     comments="# "                    # Prefix for header/footer
# )

# ===========================================================================================================================


np.savetxt("B:/BCA I/CFN/Assignment_I.txt", a, fmt="%d", header="Day 6", footer="Workshop")
a1=np.loadtxt("B:/BCA I/CFN/Assignment_I.txt",skiprows=1)
print(a1)


# savetxt = saves array to .txt
# header = add header line in the text file
# footer = add footer line in the text file
# a = The NumPy array you want to save
# fmt="%d" = Format for saving data: %d means integer format
# np.loadtxt = Loads data from a text file into a NumPy array

# skiprows=1 = Skips the first line (usually the header) before reading data





[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


FileNotFoundError: [Errno 2] No such file or directory: 'B:/BCA I/CFN/Assignment_I.txt'

Arithemtic Operations


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])


In [ ]:
print(a+b) # Addition

[5 7 9]


In [ ]:
print(a-b) # subtraction

[-3 -3 -3]


In [ ]:
print(a*b) # Multiplication

[ 4 10 18]


In [ ]:
print(a / b) # True Division -- Returns a float result, even if both inputs are integers


[0.25 0.4  0.5 ]


In [ ]:
print(a // b) #- Result type depends on inputs:
# - If both are integers → integer result.
# - If floats → still floored, but returned as float


[0 0 0]


In [ ]:
print( b % a) #- Remainder of division

[0 1 0]


In [ ]:
# exponent -> power

print(a**2)

[1 4 9]


In [ ]:
# universal Function -> ufuncs

arr = np.array([1,4,9,16])



In [ ]:
# Squre root -> np.squrt()

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
# exponentional -> np.exp -> e^x -> x is any integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
# sin fuction

import numpy as np

a = np.array([90])
b = np.sin(np.radians(a))  # Convert degrees to radians before applying sin
print(b)



[1.]


 Indexing and Slicing

In [ ]:
# Indexing

a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)


# Normal indexing
print(a[4])

# Negative Indexing

print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
4
9


In [ ]:
# Multidimensional  Indexing

# Create a 3x3 matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Accessing individual elements
print(matrix[0][1])   # Row 0, Column 1 → 2
print(matrix[2][1])   # Row 2, Column 1 → 8
print("------------")
# Row slicing
print(matrix[1:3])    # Rows 1 to 2 (end index 3 is exclusive)
print("------------")

print(matrix[1:3:2])  # Rows 1 to 2, step = 2 → only Row 1
print("------------")

print(matrix[::2])    # Every 2nd row → Rows 0 and 2
print("------------")

print(matrix[0:1])    # Only Row 0
print("------------")

# Row and column slicing
print(matrix[0:2, :])  
# Rows 0 and 1, all columns
# First part (0:2) → rows 0 and 1
# Second part (:) → all columns

print(matrix[1:, 1:]) 
# From Row 1 onward, from Column 1 onward
# → Submatrix [[5, 6], [8, 9]]


2
8
------------
[[4 5 6]
 [7 8 9]]
------------
[[4 5 6]]
------------
[[1 2 3]
 [7 8 9]]
------------
[[1 2 3]]
------------
[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]


In [ ]:
# Fancy array:Fancy indexing means using arrays/lists
# of indices to access multiple elements of another array at once. 

a=np.array([1,'s',"sample",3.1])
idx=[0,2]
print(a[idx])



['1' 'sample']


In [ ]:
# Boolean indexing:Boolean indexing is essentially filtering arrays by conditions.

arr8777=np.array([1,4,5,3,8])

print(arr8777[arr8777>2])
print(arr8777[arr8777 % 2==0])
print(arr8777[arr8777 %2 !=0])



[4 5 3 8]
[4 8]
[1 5 3]


In [ ]:
# Advanced indexing

In [ ]:
# np.take -> built in function to perform indexing and slicing

arr=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))


[10 30]


In [ ]:
# Iterating with nditer()

# - It stands for NumPy N-Dimensional Iterator.
# - It allows you to iterate over every element of an array, regardless of its shape.


arr=np.array([[4,5],[6,7]])

In [ ]:
for x in np.nditer(arr):
    print(x)

4
5
6
7


In [ ]:
# ndenumerate() -> both index + value

# - It’s a generator that yields pairs of (index, value).
# - The index is a tuple representing the position in the array.
# - Useful when you need both the element and its location.




for ind, x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 4
(0, 1) 5
(1, 0) 6
(1, 1) 7


In [ ]:
# Slicing

print(a[1:4]) # a[1:4] 1= starting index and 4= ending index
print(a[1:4:2]) # a[1:4:2] 1= starting index and 4= ending index 2 =
print(a[::2])  # ::2 2=step
print(a[::-1]) # ::-1 -1=step
print(a[-1:-4:-1])


['s', 'sample', 3.1]
['s', 3.1]
[1, 'sample']
[3.1, 'sample', 's', 1]
[3.1, 'sample', 's']


In [ ]:
# Views Vs Copies

# Python Lists → slicing makes a copy.
# NumPy arrays → slicing makes a view (unless you explicitly call .copy()).

arr=np.array([1,2,3,4,5])
view= arr[1:3]
view

array([2, 3])

In [ ]:
view[0]=200

In [ ]:
view


array([200,   3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
# Copies

copy= arr[1:3].copy()
copy

array([200,   3])

In [ ]:
copy[0]=2

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
arr = np.array([[1,2],[4,5]])
arr

array([[1, 2],
       [4, 5]])

In [ ]:
print(arr.transpose())

[[1 4]
 [2 5]]


In [ ]:
# Swapaxes -> swap 2 specific axes in a matrix

arr=np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap = np.swapaxes(arr,0,2)
swap.shape

(2, 2, 1)

In [ ]:
# concatenation

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

c= np.concatenate((a,b))
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Joining two array()
# 1.hstack()
# 2.vstack()
# 3.block()

# Here is a comparison table for the three NumPy functions used to join arrays:

# | Function       | Joins Along | Description                | Example Output Shape |
# |----------------|-------------|----------------------------|-----------------------|
# | `np.hstack()`  | Columns     | Side-by-side merge         | `[rows, cols1 + cols2]` |
# | `np.vstack()`  | Rows        | Top-bottom merge           | `[rows1 + rows2, cols]` |
# | `np.block()`   | Grid layout | Matrix-style block joining | Flexible (grid-based) |



import numpy as np
a1 = np.arange(6,12).reshape(2,3)
print("a1 = ",a1)

a2 = np.arange(8).reshape(2,4)
print("a2  = " ,a2 )

# Lists → slicing makes a copy.

# NumPy arrays → slicing makes a view (unless you explicitly call .copy()).
print("")

print("Vertical Joining")

b1 = np.arange(6).reshape(2,3)
b2 = np.arange(6,12).reshape(2,3)
a44 = np.vstack([b1, b2])          # match columns
print(a44)

print("")

print("Horizontal Joining\n")

a3 = np.hstack([a1, a2])
print(a3)


print("")

print("Block Joining\n")


a5 = np.block([a1, a2])
print(a5)




a1 =  [[ 6  7  8]
 [ 9 10 11]]
a2  =  [[0 1 2 3]
 [4 5 6 7]]

Vertical Joining
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Horizontal Joining

[[ 6  7  8  0  1  2  3]
 [ 9 10 11  4  5  6  7]]

Block Joining

[[ 6  7  8  0  1  2  3]
 [ 9 10 11  4  5  6  7]]


In [ ]:
# Spliting Arrays:


# split() function :- np.split() is a NumPy function used to divide an array into multiple sub-arrays


# it divides the array into subarray

arr=np.arange(15)
arr1=np.split(arr,5)
print(arr1)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]


In [ ]:
# Repeating:

arr=np.arange(8)
arr1=np.repeat(arr,2)
print(arr1)

[0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7]


In [ ]:
# tile -> repeat my whole array

print(np.tile(arr,2))

[0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7]


In [ ]:
# Aggregate Functions:

# Opertions in arrays in 1-D

# sum,max,min,sort,mean,std,argum

a1=np.array([12,24,36,56,76,98,95])
print(a1)
print(a1.sum())
print(a1.max())
print(a1.min())
a1.sort()
print("Sorted Array:",a1)
print(a1.mean())
print(a1.argsort())  #arg means index
print(a1.argmax())
print(a1.argmin())

[12 24 36 56 76 98 95]
397
98
12
Sorted Array: [12 24 36 56 76 95 98]
56.714285714285715
[0 1 2 3 4 5 6]
6
0


In [ ]:
print(np.square(a1))   
print(np.sqrt(a1))      
print(np.log(a1))
print(np.log10(a1))
print(np.log2(a1))
print(np.exp(a1))

[ 144  576 1296 3136 5776 9025 9604]
[3.46410162 4.89897949 6.         7.48331477 8.71779789 9.74679434
 9.89949494]
[2.48490665 3.17805383 3.58351894 4.02535169 4.33073334 4.55387689
 4.58496748]
[1.07918125 1.38021124 1.5563025  1.74818803 1.88081359 1.97772361
 1.99122608]
[3.5849625  4.5849625  5.169925   5.80735492 6.24792751 6.56985561
 6.61470984]
[1.62754791e+05 2.64891221e+10 4.31123155e+15 2.09165950e+24
 1.01480039e+33 1.81123908e+41 3.63797095e+42]


In [ ]:
print(np.round(2.678))    # 3.0
print(np.floor(2.678))    # 2.0
print(np.ceil(2.678))     # 3.0
print(np.trunc(2.678))    # 2.0

3.0
2.0
3.0
2.0


In [ ]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     # [1 2 5 3 8 4 2 5]
print(np.sort(arr))    # [-5 -4  1  2  2  3  5  8]
print(np.unique(arr))  # [-5 -4  1  2  3  5  8]

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]


In [ ]:
# In 2-D

a=np.arange(10,19).reshape(3,3)
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

# now perform all above example on simmiler way



[[10 11 12]
 [13 14 15]
 [16 17 18]]
126
[39 42 45]
[33 42 51]


In [ ]:
# Cumulative Opertions -> running total
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
print(np.cumsum(arr))

[1 3 6]


In [ ]:
print(np.cumprod(arr))

[1 2 6]


In [ ]:
# Conditional based choices:
# -------------------------------------


a1 = np.array([[1, 2, -3], [-8, 6, -4], [6, -4, 6]])
print("Original Matrix:\n", a1)

# Apply conditional transformation:
# If element > 0 → multiply by 2
# Else → cube the element
b = np.where(a1 > 0, 2 * a1, a1 ** 3)
print("Transformed Matrix:\n", b)

Original Matrix:
 [[ 1  2 -3]
 [-8  6 -4]
 [ 6 -4  6]]
Transformed Matrix:
 [[   2    4  -27]
 [-512   12  -64]
 [  12  -64   12]]


In [ ]:
# argwhere : row-column postion for 2d arrays
arr=np.array([10,25,35,50])
print(arr)
print(np.argwhere(arr>20))

[10 25 35 50]
[[1]
 [2]
 [3]]


In [ ]:
mask = np.logical_and(arr>15,arr<35)
mask

array([False,  True, False, False])

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
mask=np.logical_and(arr >3 ,arr<6)

In [ ]:
mask

array([False, False, False, False])

In [ ]:
arr[mask]

array([], dtype=int64)

In [ ]:
arr2 = np.array([0,1,5,0,5])
arr2

array([0, 1, 5, 0, 5])

In [ ]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [ ]:
# Dealing with missisng value
# ------------------------------------

# np.nan -> not a nummebr

In [ ]:
a= np.array([1,2,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [ ]:
# np.inf and -np.inf  -> positive and negtive infinate

In [ ]:
# np.isnan
# np.isinf
# np.isfinite

# ---> these are the function used to dettect any null values , infinite value or finite value

In [ ]:
print(np.isnan(a))

[False False  True False]


In [ ]:
b=np.array([1,np.nan,np.inf,10.2,40])

In [ ]:
print(np.logical_or(np.isinf(b), np.isnan(b)))

[False  True  True False False]


In [ ]:
np.nan_to_num(b) # remove Nan/infinite values.


array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])

In [ ]:
new_b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# Axes in Multi-dimensional Arrays
# ----------------------------------------


# - 1D array has 1 axis (axis0).
# - 2D array has 2 axes (axis0 = rows, axis1 = columns)
# - 3D array has 3 axes (axis0 = depth/layer, axis1 = rows in each layer, axis2 = columns in each layer)

In [ ]:
# 3D array
arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])

print(arr3D)
print(arr3D.shape)

#Indexing
print(arr3D[0][1][1])   #4
print(arr3D[1][2][1])   #12

print(arr3D[:, :, 0])        #first col from both layers
print(arr3D[:, 0, :])        #first row from both layers

#Manipulating data
arr3D[:, 0, :] = 99          #change first row to store 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
4
12
[[ 1  3  5]
 [ 7  9 11]]
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [ ]:
# Common Data Types in Numpy
# -------------------------------


# - Integers: int32, int64
# - Floating point nums: float32, float64
# - Boolean: bool
# - Complex nums: complex64, complex128
# - String: S (byte-str) & U (unicode-str)
# - Object: generic python objects - object

In [ ]:
#Common Data Types
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes)        # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)


# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)


int32
float64
<U5
20
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


In [ ]:
# 1. Vectorization  
# Vectorization is the process of applying operations to entire arrays or sequences of data at once, rather than iterating through individual elements using explicit loops.


In [ ]:
# np.vectorize() -> convert a regular function to be applied on an array

# Ex1
arr=np.array([10,25,35,50])
def squre(x):
  return x*x

vfunc = np.vectorize(squre)
arr
print(vfunc(arr))

[ 100  625 1225 2500]


In [ ]:
# Ex2

arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       #square of all nums
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays


[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [ ]:
# Benefits

# - When you want to apply a custom function to every element.
# - For readability.

# Disadvantages


# - It's not faster than a loop.
# - It only makes syntax cleaner, but does not improve speed like real vectorized NumPy functions.


In [ ]:
# Broadcasting  

# Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes without explicitly reshaping them. It conceptually “stretches” the smaller array across the larger one so element-wise operations can occur.

# Broadcasting Conditions
# For broadcasting to work, the dimensions of the arrays must be compatible. NumPy compares shapes element-wise, starting from the trailing (rightmost) dimension and moving left.

# Two dimensions are compatible when:
# They are equal, or
# One of them is 1.

# If these conditions are not met, NumPy raises a ValueError.

In [ ]:
# Ex1

image = np.array([[200,150],[100,250]])
image.shape



(2, 2)

In [ ]:
image

array([[200, 150],
       [100, 250]])

In [ ]:
brightness = image + 50

print(image)

[[200 150]
 [100 250]]


In [ ]:
# Ex2
arr_mul10 = arr * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[100 250 350 500]
[[2 4 6]
 [5 7 9]]


In [ ]:
# Vector Normalization
# ---------------------------


arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

print((arr - mean) / std_dev)

#column wise
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr-mean) / std_dev)